# -*- coding: utf-8 -*-
"""Assignment_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13abpROL60ukDKQCw4gxpgSVKkq6BXuNg

# Basic Python

## 1. Split this string
"""

s = "Hi there Sam!"
a = s.split()
print(a)



"""## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.
"""

planet = "Earth"
diameter = 12742
txt="The diameter of {} is {} kilometers".format (planet,diameter)
print(txt)



"""## 3. In this nest dictionary grab the word "hello"
"""

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
a=d['k1'][3]['tricky'][3]['target'][3]
print(a)



"""# Numpy"""

import numpy as np

"""## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?
"""

import numpy as np
array=np.zeros(10)
print(array)

import numpy as np
array=np.ones(10)*5
print(array)

"""## 5. Create an array of all the even integers from 20 to 35"""

import numpy as np
array=np.arange(20,35,2)
print(array)

"""## 6. Create a 3x3 matrix with values ranging from 0 to 8"""

import numpy as np
matrix=np.arange(0,9).reshape(3,3)
print(matrix)

"""## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])
"""

import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
con=np.concatenate([a,b])
print(con)

"""# Pandas

## 8. Create a dataframe with 3 rows and 2 columns
"""

import pandas as pd
data=[['Arul',20],['Simi',32],['Beno',7]]
df=pd.DataFrame(data,columns=['Name','Age'])
print(df)



"""## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023"""

import pandas as pd
date=pd.date_range(start='01-01-2023',end='25-12-2023')
print(date)

"""## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]
"""

import pandas as pd
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df=pd.DataFrame(lists,columns=['SI.NO','Name','Rollno'])
print(df)

